Repository Talent-Catalog/talentcatalog, pull requests merged in 2023-06, with the labels that each got.

#59 54 nested json from salesforce eg accountwebsite not returning in java
  server/src/main/java/org/tbbtalent/server/model/sf/Opportunity.java
  server/src/main/java/org/tbbtalent/server/service/db/impl/SalesforceServiceImpl.java
  server/src/test/java/org/tbbtalent/server/model/sf/OpportunityTest.java
Labels: best practice

#28 unit tests for branding admin api
  server/src/main/java/org/tbbtalent/server/api/admin/BrandingAdminApi.java
  server/src/main/java/org/tbbtalent/server/service/db/impl/BrandingServiceImpl.java
  server/src/test/java/org/tbbtalent/server/api/admin/BrandingAdminApiTest.java
  server/src/test/java/org/tbbtalent/server/model/db/BrandingInfoTest.java
  server/src/test/java/org/tbbtalent/server/service/db/impl/BrandingServiceImplTest.java
Labels: testing

#127 All of these actions are now reflecting properly in the audit fields,…
  server/src/main/java/org/tbbtalent/server/service/db/impl/CandidateAttachmentsServiceImpl.java
  server/src/main/java/org/tbbtalent/server/service/db/impl/CandidateJobExperienceImpl.java
  server/src/main/java/org/tbbtalent/server/service/db/impl/CandidateOccupationServiceImpl.java
  server/src/main/java/org/tbbtalent/server/service/db/impl/CandidateServiceImpl.java
Labels: bug
