Repository Talent-Catalog/talentcatalog, pull requests merged in 2024-04, with the labels that each got.

#814 348 highlight the es search term in the candidate profile
  ui/admin-portal/src/app/components/candidates/view/additional-info/view-candidate-additional-info.component.html
  ui/admin-portal/src/app/components/candidates/view/certification/view-candidate-certification.component.html
  ui/admin-portal/src/app/components/candidates/view/contact/view-candidate-contact.component.html
  ui/admin-portal/src/app/components/candidates/view/education/view-candidate-education.component.html
  ui/admin-portal/src/app/components/candidates/view/language/view-candidate-language.component.html
  ui/admin-portal/src/app/components/candidates/view/media/view-candidate-media-willingness.component.html
  ui/admin-portal/src/app/components/candidates/view/occupation/experience/view-candidate-job-experience.component.html
  ui/admin-portal/src/app/components/candidates/view/registration/view-candidate-registration.component.html
  ui/admin-portal/src/app/components/candidates/view/skill/view-candidate-skill.component.html
  ui/admin-portal/src/app/components/candidates/view/survey/view-candidate-survey.component.html
  ui/admin-portal/src/app/components/search/define-search/define-search.component.ts
  ui/admin-portal/src/app/directives/directive.module.ts
  ui/admin-portal/src/app/directives/highlight-search.directive.ts
  ui/admin-portal/src/app/services/search-query.service.ts
  ui/admin-portal/src/scss/_variables.scss
  ui/admin-portal/src/styles.scss
Labels: enhancement

#822 818 make admin portal reaction pickers open on the buttons instead of as a centered modal
  ui/admin-portal/src/app/components/chat/create-update-post/create-update-post.component.html
  ui/admin-portal/src/app/components/chat/create-update-post/create-update-post.component.ts
  ui/admin-portal/src/app/components/chat/view-chat-posts/view-chat-posts.component.ts
  ui/admin-portal/src/app/components/chat/view-post/view-post.component.html
  ui/admin-portal/src/app/components/chat/view-post/view-post.component.scss
  ui/admin-portal/src/app/components/chat/view-post/view-post.component.ts
  ui/candidate-portal/src/app/components/chat/create-update-post/create-update-post.component.html
  ui/candidate-portal/src/app/components/chat/create-update-post/create-update-post.component.ts
  ui/candidate-portal/src/app/components/chat/view-post/view-post.component.html
  ui/candidate-portal/src/app/components/chat/view-post/view-post.component.ts
Labels: best practice, front end only

#866 add caching for users
  server/build.gradle
  server/src/main/java/org/tctalent/server/cache/CacheLogger.java
  server/src/main/java/org/tctalent/server/cache/UserKeyGenerator.java
  server/src/main/java/org/tctalent/server/cache/UsernameKeyGenerator.java
  server/src/main/java/org/tctalent/server/configuration/EhcacheConfig.java
  server/src/main/java/org/tctalent/server/repository/db/UserRepository.java
  server/src/main/resources/application.yml
  server/src/main/resources/ehcache.xml
Labels: best practice

#886 847 id emailphone namenumber search slowness
  server/src/main/java/org/tctalent/server/repository/db/CandidateRepository.java
  server/src/main/resources/db/migration/V1_312__perf_improvements_for_name_search.sql
Labels: tech debt, best practice
