Repository Talent-Catalog/talentcatalog, pull requests merged in 2025-04, with the labels that each got.

#2009 2008 Change cursor to pointer
  ui/candidate-portal/src/app/components/profile/view/tab/services/duolingo/duolingo.component.scss
  ui/candidate-portal/src/app/components/profile/view/tab/services/services.component.scss
Labels: front end only

#2054 update country name for the democratic republic of the congo
  server/src/main/resources/db/migration/V1_354__update_country_names.sql
Labels: data

#2064 2063 back out removing migration occupation field
  server/src/main/java/org/tctalent/server/api/admin/CandidateBuilderSelector.java
  server/src/main/java/org/tctalent/server/api/admin/CandidateOccupationAdminApi.java
  server/src/main/java/org/tctalent/server/api/portal/CandidateOccupationPortalApi.java
  server/src/main/java/org/tctalent/server/api/portal/CandidatePortalApi.java
  server/src/main/java/org/tctalent/server/model/db/CandidateOccupation.java
  server/src/main/java/org/tctalent/server/model/es/CandidateEs.java
  server/src/main/java/org/tctalent/server/repository/db/CandidateSpecification.java
  server/src/main/resources/db/migration/V1_353__remove_migration_occupation_field.sql
  server/src/main/resources/db/migration/V1_353__update_country_names.sql
Labels: bug

#2085 2067 tc logo on login screen and favicon
  ui/admin-portal/src/app/components/login/login.component.html
  ui/admin-portal/src/app/components/login/login.component.scss
  ui/admin-portal/src/app/components/login/login.component.ts
  ui/admin-portal/src/assets/images/tc-logo-2.png
  ui/admin-portal/src/assets/images/tc-logo.png
  ui/admin-portal/src/favicon.ico
  ui/admin-portal/src/favicon_old.ico
  ui/candidate-portal/src/favicon.ico
  ui/candidate-portal/src/favicon_old.ico
  ui/public-portal/src/favicon.ico
  ui/public-portal/src/favicon_old.ico
Labels: UI/UX
